project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Zimmerman Lab"

  page-footer:
    left: "{{< fa regular copyright >}} 2023 Naupaka Zimmerman, [{{< fa brands creative-commons-by >}} CC-BY 4.0](https://creativecommons.org/licenses/by/4.0/)"
    right: "This page is built with ï¸ğŸŒ±ğŸ„ğŸ“Š and [Quarto](https://quarto.org/)."

  sidebar:
    logo: files/zlab_logo.png
    pinned: true
    align: center
    style: "docked"
    collapse-level: 1
    contents:

      - text: "People"
        href: people/index.qmd

      - text: "Projects"
        href: projects/index.qmd

      - text: "Teaching"
        href: teaching/index.qmd

      - text: "Open Science"
        hrf: open_science/index.qmd

      - text: "Join the Lab"
        href: join.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


